"""Small DB-API compatibility layer for SQLite development and Neon Postgres."""

from __future__ import annotations

import sqlite3

import psycopg
from psycopg.rows import dict_row


INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)
DATABASE_ERRORS = (sqlite3.Error, psycopg.Error)


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('consumer','business','admin')),
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  created_by_admin INTEGER REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON users (LOWER(email));
CREATE TABLE IF NOT EXISTS businesses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  wallet_balance INTEGER NOT NULL DEFAULT 0,
  low_balance_threshold INTEGER NOT NULL DEFAULT 2000,
  needs_top_up INTEGER NOT NULL DEFAULT 0,
  is_approved INTEGER NOT NULL DEFAULT 0,
  is_blocked INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  redemption_fee INTEGER
);
CREATE TABLE IF NOT EXISTS consumer_profiles (
  user_id INTEGER PRIMARY KEY REFERENCES users(id),
  area TEXT,
  favorite_categories TEXT NOT NULL DEFAULT '',
  notifications_enabled INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS consumer_devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  revoked_at TEXT
);
CREATE TABLE IF NOT EXISTS deals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  terms TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  redemption_limit INTEGER NOT NULL CHECK(redemption_limit > 0),
  redemption_count INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(id),
  deal_id INTEGER NOT NULL REFERENCES deals(id),
  created_at TEXT NOT NULL,
  PRIMARY KEY (user_id, deal_id)
);
CREATE TABLE IF NOT EXISTS codes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id INTEGER NOT NULL REFERENCES deals(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  value TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK(status IN ('active','redeemed','expired')) DEFAULT 'active',
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  redeemed_at TEXT,
  redeemed_by INTEGER REFERENCES users(id),
  device_id INTEGER REFERENCES consumer_devices(id)
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  price_kobo INTEGER,
  product_url TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS product_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  secure_url TEXT,
  public_id TEXT,
  storage_provider TEXT NOT NULL DEFAULT 'local',
  sort_order INTEGER NOT NULL CHECK(sort_order BETWEEN 1 AND 5),
  created_at TEXT NOT NULL,
  UNIQUE(product_id, sort_order)
);
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id),
  amount INTEGER NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('topup','redemption','adjustment')),
  status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected','posted')),
  reference TEXT NOT NULL UNIQUE,
  note TEXT,
  created_at TEXT NOT NULL,
  approved_at TEXT,
  approved_by INTEGER REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS ledger_entries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id),
  deal_id INTEGER NOT NULL REFERENCES deals(id),
  code_id INTEGER NOT NULL UNIQUE REFERENCES codes(id),
  fee_charged INTEGER NOT NULL,
  wallet_balance_after INTEGER NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS platform_settings (
  setting_key TEXT PRIMARY KEY,
  integer_value INTEGER NOT NULL,
  updated_at TEXT NOT NULL,
  updated_by INTEGER REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id INTEGER NOT NULL REFERENCES users(id),
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id INTEGER NOT NULL,
  details TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS categories_name_lower_idx ON categories (LOWER(name));
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS login_attempts (
  attempt_key TEXT PRIMARY KEY,
  failures INTEGER NOT NULL DEFAULT 0,
  blocked_until TEXT,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS deals_active_idx ON deals(is_active, expires_at);
CREATE INDEX IF NOT EXISTS codes_value_idx ON codes(value);
CREATE INDEX IF NOT EXISTS codes_user_status_idx ON codes(user_id, status, created_at);
CREATE INDEX IF NOT EXISTS codes_device_status_idx ON codes(device_id, status, created_at);
CREATE INDEX IF NOT EXISTS products_business_active_idx ON products(business_id, is_active);
CREATE INDEX IF NOT EXISTS product_images_product_idx ON product_images(product_id, sort_order);
CREATE INDEX IF NOT EXISTS password_reset_user_idx ON password_reset_tokens(user_id, expires_at);
"""


class PostgresCursor:
    """Expose the small sqlite cursor surface the application already uses."""

    def __init__(self, cursor, connection):
        self._cursor = cursor
        self._connection = connection

    @property
    def lastrowid(self):
        # Every generated application id uses a Postgres identity sequence.
        return self._connection.execute("SELECT LASTVAL() AS id").fetchone()["id"]

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgresDatabase:
    """Translate SQLite qmark placeholders for the existing query layer."""

    def __init__(self, database_url):
        self._connection = psycopg.connect(database_url, autocommit=True, row_factory=dict_row)

    def execute(self, query, params=None):
        # psycopg treats every percent sign in the SQL text as the start of a
        # parameter placeholder. Escape literal percent signs first (such as
        # ``LIKE 'PSTK-%'``), then translate the application's SQLite qmarks.
        query = query.replace("BEGIN IMMEDIATE", "BEGIN").replace("%", "%%").replace("?", "%s")
        cursor = self._connection.execute(query, params)
        return PostgresCursor(cursor, self._connection)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()
